### ISSUE TITLE
Error running prepper

### ISSUE THREAD

**Issue by Freeport2** [billdonner/prepper#2]
Didn't stop Prepper from running.
<img width="1024" alt="Screenshot 2023-06-21 at 11 27 16 AM" src="https://github.com/billdonner/prepper/assets/135785452/f49dfcc5-29c9-4d50-b052-bfc29f6d2c5a">

**Comment by billdonner** [comment]
this is just a warning and you should be running fine even with it

however I fixed it and you should pull
